[package]
name = "cce-list"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "0165aa4fe0acf1a0814081d0a0572e5cdc71301a" }
calloop = "0.13.0"
wayland-client = { version = "0.31", features = ["system"] }
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
cce-vault = { git = "https://github.com/lsgalante/cce-vault.git", rev = "3d8130142469b9a1c7941a3bd3d6da3eeb79be2a" }

[[bin]]
name = "cce-list"
path = "src/main.rs"
