[package]
name = "cce-list"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "69388cfb769c61ae7221c9ba6aeb37f8c6768210" }
calloop = "0.13.0"
wayland-client = { version = "0.31", features = ["system"] }
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
cce-vault = { git = "https://github.com/lsgalante/cce-vault.git", rev = "acf0e24b015812bd9a83022085cc78cfa9acd766" }

[[bin]]
name = "cce-list"
path = "src/main.rs"
